# -*- coding: utf-8 -*-
"""
Introdução a Machine Learning e Classificação - 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNvuZmre0mDEJgTBBXBzvptPtth7q_IX
"""

# Importações necessárias
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

# Definição dos dados
# features: [pelo longo?, perna curta?, faz auau?]
porcos = [
    [0, 1, 0],
    [0, 1, 1],
    [1, 1, 0]
]

cachorros = [
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
]

# 1 => porco, 0 => cachorro
dados = np.array(porcos + cachorros)
classes = np.array([1] * len(porcos) + [0] * len(cachorros))

# Treinamento do modelo
model = LinearSVC()
model.fit(dados, classes)

# Predição para um animal misterioso
animal_misterioso = np.array([1, 1, 1])
predicao = model.predict([animal_misterioso])
print(f"Predição para o animal misterioso: {predicao[0]}")

# Testes de predição
testes = np.array([
    [1, 1, 1],
    [1, 1, 0],
    [0, 1, 1]
])
testes_classes = np.array([0, 1, 1])

# Realização das previsões
previsoes = model.predict(testes)

# Cálculo da taxa de acerto
taxa_de_acerto = accuracy_score(testes_classes, previsoes)
print(f"Taxa de acerto: {taxa_de_acerto * 100:.2f}%")
